title: "Arti's Site"
description: "Where someone whose online name is 'arti_creep' tells stories." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://arti-dev.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "boomcreeper296@gmail.com"
#twitter_username: "twitteruser"
#github_username: "githubuser"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

# Build settings
theme: minima
#remote_theme: jekyll/minima
#
#minima:
#  skin: dark

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
#  - jekyll-remote-theme

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: Other

